Groups:
  default:
    Priority: 3
    JoinMessage: '&a+ &f%player_displayname%'
    LeaveMessage: '&c- &f%player_displayname%'
    DeathMessage: '&c♰ player_displayname%'
  VIP:
    Priority: 0
    JoinMessage: '&a+ &6%player_displayname%'
    LeaveMessage: '&c- &6%player_displayname%'
    DeathMessage: '&c♰ &6%player_displayname%'
